language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install ffmpeg gstreamer0.10-ffmpeg

script:
 - dotnet restore Xabe.FFMpeg.Test/
 - dotnet test Xabe.FFMpeg.Test/
 - dotnet restore Xabe.FFMpeg/
 - dotnet pack Xabe.FFMpeg
 - dotnet build Xabe.FFMpeg/ -c Release
