language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
  - sudo add-apt-repository ppa:jon-severinsson/ffmpeg
  - sudo apt-get update
  - sudo apt-get install ffmpeg
  - sudo apt-get install frei0r-plugins

script:
 - dotnet restore Xabe.FFMpeg.Test/
 - dotnet test Xabe.FFMpeg.Test/
 - dotnet restore Xabe.FFMpeg/
 - dotnet pack Xabe.FFMpeg
 - dotnet build Xabe.FFMpeg/ -c Release
