language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get -qq update
  - sudo apt-get install FFmpeg gstreamer0.10-FFmpeg libav-tools libgdiplus libavcodec-extra  libtheora-dev -y
  - sudo apt-cache policy libav-tools
script:
 - ./build.sh
